# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [30]:
url = "https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv"
df = pd.read_csv(url,sep=',')
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
1,2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2,2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
3,2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
4,2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 4.  What is the frequency of the dataset?

In [22]:
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
1,2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2,2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
3,2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
4,2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 5. Set the column Date as the index.

In [31]:
df.set_index('Date',inplace=True)
df.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 6. What is the type of the index?

In [ ]:
df.index.dtype # Object

dtype('O')

### Step 7. Set the index to a DatetimeIndex type

In [32]:
df.index = pd.to_datetime(df.index)

In [33]:
df.index.dtype

dtype('<M8[ns]')

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [ ]:
monthly = df.resample('ME').sum(min_count=1) #
# if all values in a resampled period are NaN (missing), the result will be NaN instead of 0.
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387.0,-16805.0,-1582.0,3188.0,8688.0,6841.0,1849.0,-6510.0
2011-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31,-23657.0,-16659.0,-6999.0,2395.0,13817.0,9335.0,4483.0,-7443.0
2012-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [37]:
monthly.dropna(axis='index',how='all', inplace=True)

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [40]:
yearly = monthly.resample('A').sum()
yearly.head()

C:\Users\jade\AppData\Local\Temp\ipykernel_22048\479748006.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  yearly = monthly.resample('A').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-12-31,-42044.0,-33464.0,-8581.0,5583.0,22505.0,16176.0,6332.0,-13953.0
2012-12-31,-23929.0,-22012.0,-1915.0,785.0,9828.0,12491.0,-2663.0,-13316.0
2013-12-31,8052.0,-5562.0,13615.0,4180.0,-24460.0,-14209.0,-10251.0,-12227.0
2014-12-31,-17011.0,-15124.0,-1887.0,-6141.0,-14400.0,-19014.0,4614.0,-37552.0
2015-12-31,-36337.0,-25116.0,-11221.0,-12474.0,-28678.0,-34571.0,5893.0,-77489.0