# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [ ]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [135]:
data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data",sep="\s+") #
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [136]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Yr      6574 non-null   int64
 1   Mo      6574 non-null   int64
 2   Dy      6574 non-null   int64
 3   RPT     6568 non-null   float64
 4   VAL     6571 non-null   float64
 5   ROS     6572 non-null   float64
 6   KIL     6569 non-null   float64
 7   SHA     6572 non-null   float64
 8   BIR     6574 non-null   float64
 9   DUB     6571 non-null   float64
 10  CLA     6572 non-null   float64
 11  MUL     6571 non-null   float64
 12  CLO     6573 non-null   float64
 13  BEL     6574 non-null   float64
 14  MAL     6570 non-null   float64
dtypes: float64(12), int64(3)
memory usage: 770.5 KB

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [137]:
data['date_string'] = '19' + data.Yr.astype(str) + '-' + data.Mo.astype(str) + '-' + data.Dy.astype(str)

In [138]:
data['date'] = pd.to_datetime(data['date_string'], format='%Y-%m-%d')
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date_string,date
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-1-1,1961-01-01
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-1-2,1961-01-02
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-1-3,1961-01-03
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-1-4,1961-01-04
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-1-5,1961-01-05

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [106]:
data.date.dtype

dtype('<M8[ns]')

In [139]:
data.set_index('date',inplace=True)
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date_string
date,,,,,,,,,,,,,,,,
1961-01-01,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-1-1
1961-01-02,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-1-2
1961-01-03,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-1-3
1961-01-04,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-1-4
1961-01-05,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-1-5

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [108]:
data.isna().sum()

Yr             0
Mo             0
Dy             0
RPT            6
VAL            3
ROS            2
KIL            5
SHA            2
BIR            0
DUB            3
CLA            2
MUL            3
CLO            1
BEL            0
MAL            4
date_string    0
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [ ]:
data.loc[:,'RPT':'MAL'].notna().sum().sum() #
# isna() == False

78857

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [141]:
rd = data.loc[:,'RPT':'MAL']

In [142]:
rd.mean().mean()

10.227982360836938

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [143]:
loc_stats = rd.describe()
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [144]:
day_stats = rd.head().T.describe()
day_stats

date   1961-01-01  1961-01-02  1961-01-03  1961-01-04  1961-01-05
count   11.000000   11.000000   11.000000   12.000000   12.000000
mean    13.018182   11.336364   11.641818    6.619167   10.630000
std      2.808875    3.188994    3.681912    3.198126    2.445356
min      9.290000    6.500000    6.170000    1.790000    6.170000
25%     10.540000    9.730000    9.315000    4.570000    9.807500
50%     13.170000   10.830000   11.250000    5.855000   11.170000
75%     15.000000   13.225000   12.730000    9.117500   12.170000
max     18.500000   17.540000   18.500000   11.750000   13.330000

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [145]:
data[data.Mo == 1].loc[:,'RPT':'MAL'].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [ ]:
ds = data.resample('A').mean(numeric_only=True) #
ds.head()

C:\Users\jade\AppData\Local\Temp\ipykernel_11128\203793943.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  ds = data.resample('A').mean(numeric_only=True)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-12-31,61.0,6.526027,15.720548,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-12-31,62.0,6.526027,15.720548,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-12-31,63.0,6.526027,15.720548,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,64.0,6.513661,15.756831,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,65.0,6.526027,15.720548,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644

### Step 13. Downsample the record to a monthly frequency for each location.

In [147]:
ds = data.resample('ME')
ds.mean(numeric_only=True)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-01-31,61.0,1.0,16.0,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02-28,61.0,2.0,14.5,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03-31,61.0,3.0,16.0,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04-30,61.0,4.0,15.5,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-31,61.0,5.0,16.0,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-31,78.0,8.0,16.0,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-30,78.0,9.0,15.5,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-31,78.0,10.0,16.0,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-30,78.0,11.0,15.5,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-31,78.0,12.0,16.0,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [148]:
ds = data.resample('W')
ds.mean(numeric_only=True)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-01-01,61.0,1.000000,1.000000,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-08,61.0,1.000000,5.000000,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-15,61.0,1.000000,12.000000,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-22,61.0,1.000000,19.000000,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-29,61.0,1.000000,26.000000,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,78.0,11.428571,17.142857,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-10,78.0,12.000000,7.000000,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-17,78.0,12.000000,14.000000,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-24,78.0,12.000000,21.000000,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-31,78.0,12.000000,28.000000,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [159]:
ds = data.resample('W')
ds.mean(numeric_only=True).shift(1,freq='D')

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-01-02,61.0,1.000000,1.000000,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-09,61.0,1.000000,5.000000,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-16,61.0,1.000000,12.000000,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-23,61.0,1.000000,19.000000,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-30,61.0,1.000000,26.000000,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-04,78.0,11.428571,17.142857,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-11,78.0,12.000000,7.000000,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-18,78.0,12.000000,14.000000,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-25,78.0,12.000000,21.000000,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1979-01-01,78.0,12.000000,28.000000,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

In [ ]:
pd.Timedelta(1,'D')

In [ ]:
ds = data.resample('W') 
ds.agg({col:['min','max','min','std'] for col in data.select_dtypes(include=['number']).columns}) #

            Yr               Mo                    Dy      ...    CLO  \
           min max min  std min max min       std min max  ...    min
date                                                       ...
1961-01-01  61  61  61  NaN   1   1   1       NaN   1   1  ...  12.58
1961-01-08  61  61  61  0.0   1   1   1  0.000000   2   8  ...   5.88
1961-01-15  61  61  61  0.0   1   1   1  0.000000   9  15  ...   2.67
1961-01-22  61  61  61  0.0   1   1   1  0.000000  16  22  ...   2.71
1961-01-29  61  61  61  0.0   1   1   1  0.000000  23  29  ...  11.04
...         ..  ..  ..  ...  ..  ..  ..       ...  ..  ..  ...    ...
1978-12-03  78  78  78  0.0  11  12  11  0.534522   1  30  ...   3.29
1978-12-10  78  78  78  0.0  12  12  12  0.000000   4  10  ...   6.75
1978-12-17  78  78  78  0.0  12  12  12  0.000000  11  17  ...   2.67
1978-12-24  78  78  78  0.0  12  12  12  0.000000  18  24  ...   4.71
1978-12-31  78  78  78  0.0  12  12  12  0.000000  25  31  ...   3.08

                        BEL                            MAL                \
                 std    min    max    min       std    min    max    min
date
1961-01-01       NaN  18.50  18.50  18.50       NaN  15.04  15.04  15.04
1961-01-08  1.704941   5.46  17.54   5.46  4.349139  10.88  16.46  10.88
1961-01-15  4.084293   5.25  20.71   5.25  5.552215   5.17  16.92   5.17
1961-01-22  4.783952   6.50  15.92   6.50  3.626584   6.79  17.96   6.79
1961-01-29  3.713368  14.04  27.71  14.04  5.210726  17.50  27.63  17.50
...              ...    ...    ...    ...       ...    ...    ...    ...
1978-12-03  6.284973   4.92  21.42   4.92  5.950112  11.50  25.75  11.50
1978-12-10  5.516405   9.54  26.08   9.54  5.600389  15.34  34.59  15.34
1978-12-17  5.487801   5.00  21.50   5.00  6.631925   6.92  22.83   6.92
1978-12-24  3.023131   3.21  19.79   3.21  5.750301  10.29  31.71  10.29
1978-12-31  5.533397   1.21  21.79   1.21  7.523148  11.96  41.46  11.96


                  std
date
1961-01-01        NaN
1961-01-08   1.773062
1961-01-15   4.692355
1961-01-22   4.237239
1961-01-29   3.874721
...               ...
1978-12-03   6.393188
1978-12-10   8.093976
1978-12-17   6.005594
1978-12-24   7.194108
1978-12-31  11.621233

[940 rows x 60 columns]